dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
  firefox: "85.0"
before_script:
  - cp decide/local_settings.travis.py decide/local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install selenium
  - pip install codacy-coverage
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.27.0-linux64.tar.gz
  - export PATH=$(pwd):$PATH
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
